import type { Flow, FlowBlock } from '../types/flow'

export function generatePython(flow: Flow): string {
  const lines: string[] = []

  lines.push('# Auto-generated by Nekonote')
  lines.push('# このコードはビジュアルフローから自動生成されています')
  lines.push('')
  lines.push('import asyncio')
  lines.push('from nekonote.runtime import browser, desktop, variables, log')
  lines.push('')
  lines.push('')
  lines.push(`async def main():`)
  lines.push(`    """${flow.name || 'Nekonote Flow'}"""`)

  if (flow.variables.length > 0) {
    lines.push('')
    for (const v of flow.variables) {
      const val = v.default === null || v.default === undefined ? 'None' : JSON.stringify(v.default)
      lines.push(`    variables.set("${v.name}", ${val})`)
    }
  }

  lines.push('')

  for (const block of flow.blocks) {
    generateBlockCode(block, lines, 1)
  }

  lines.push('')
  lines.push('')
  lines.push('if __name__ == "__main__":')
  lines.push('    asyncio.run(main())')
  lines.push('')

  return lines.join('\n')
}

function ind(level: number): string {
  return '    '.repeat(level)
}

function generateBlockCode(block: FlowBlock, lines: string[], level: number): void {
  const i = ind(level)
  const p = block.params

  if (block.label && block.label !== block.type) {
    lines.push(`${i}# ${block.label}`)
  }

  switch (block.type) {
    case 'browser.open':
      lines.push(`${i}await browser.open(${p.browser_type ? `browser_type="${p.browser_type}"` : ''}, headless=${p.headless ? 'True' : 'False'})`)
      break
    case 'browser.navigate':
      lines.push(`${i}await browser.navigate("${p.url ?? ''}")`)
      break
    case 'browser.click':
      lines.push(`${i}await browser.click("${p.selector ?? ''}")`)
      break
    case 'browser.type':
      lines.push(`${i}await browser.type("${p.selector ?? ''}", "${p.text ?? ''}")`)
      break
    case 'browser.getText':
      lines.push(`${i}${p.variable || '_text'} = await browser.get_text("${p.selector ?? ''}")`)
      if (p.variable) lines.push(`${i}variables.set("${p.variable}", ${p.variable})`)
      break
    case 'browser.wait':
      lines.push(`${i}await browser.wait("${p.selector ?? ''}", timeout=${p.timeout ?? 30000})`)
      break
    case 'browser.screenshot':
      lines.push(`${i}await browser.screenshot(${p.path ? `path="${p.path}"` : ''})`)
      break
    case 'browser.close':
      lines.push(`${i}await browser.close()`)
      break
    case 'desktop.click':
      lines.push(p.image ? `${i}await desktop.click(image="${p.image}")` : `${i}await desktop.click(x=${p.x ?? 0}, y=${p.y ?? 0})`)
      break
    case 'desktop.type':
      lines.push(`${i}await desktop.type("${p.text ?? ''}")`)
      break
    case 'desktop.hotkey':
      lines.push(`${i}await desktop.hotkey("${p.keys ?? ''}")`)
      break
    case 'desktop.screenshot':
      lines.push(`${i}await desktop.screenshot()`)
      break
    case 'desktop.findImage':
      lines.push(`${i}pos = await desktop.find_image("${p.template ?? ''}", confidence=${p.confidence ?? 0.8})`)
      break
    case 'data.setVariable':
      lines.push(`${i}variables.set("${p.name ?? ''}", ${formatVal(p.value)})`)
      break
    case 'data.log':
      lines.push(`${i}log(${formatVal(p.message)})`)
      break
    case 'data.comment':
      lines.push(`${i}# ${p.text ?? ''}`)
      break
    case 'control.wait':
      lines.push(`${i}await asyncio.sleep(${p.seconds ?? 1})`)
      break

    case 'control.if': {
      lines.push(`${i}if ${fmtCond(p.condition)}:`)
      if (block.children?.length) {
        for (const child of block.children) generateBlockCode(child, lines, level + 1)
      } else {
        lines.push(`${ind(level + 1)}pass`)
      }
      if (block.elseChildren?.length) {
        lines.push(`${i}else:`)
        for (const child of block.elseChildren) generateBlockCode(child, lines, level + 1)
      }
      break
    }
    case 'control.loop': {
      if (p.count) {
        lines.push(`${i}for _i in range(${p.count}):`)
      } else {
        lines.push(`${i}while ${fmtCond(p.condition)}:`)
      }
      if (block.children?.length) {
        for (const child of block.children) generateBlockCode(child, lines, level + 1)
      } else {
        lines.push(`${ind(level + 1)}pass`)
      }
      break
    }
    case 'control.forEach': {
      lines.push(`${i}for ${p.item_variable || 'item'} in variables.get("${p.list_variable ?? ''}", []):`)
      if (block.children?.length) {
        for (const child of block.children) generateBlockCode(child, lines, level + 1)
      } else {
        lines.push(`${ind(level + 1)}pass`)
      }
      break
    }
    case 'control.tryCatch': {
      lines.push(`${i}try:`)
      if (block.children?.length) {
        for (const child of block.children) generateBlockCode(child, lines, level + 1)
      } else {
        lines.push(`${ind(level + 1)}pass`)
      }
      lines.push(`${i}except Exception as e:`)
      lines.push(`${ind(level + 1)}variables.set("_error", str(e))`)
      if (block.elseChildren?.length) {
        for (const child of block.elseChildren) generateBlockCode(child, lines, level + 1)
      } else {
        lines.push(`${ind(level + 1)}pass`)
      }
      break
    }
  }
}

function formatVal(value: unknown): string {
  if (value === undefined || value === null) return 'None'
  if (typeof value === 'string') return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '\\r')}"`
  if (typeof value === 'boolean') return value ? 'True' : 'False'
  return String(value)
}

function fmtCond(condition: unknown): string {
  if (!condition) return 'True'
  let s = String(condition)
  if (s.startsWith('{{') && s.endsWith('}}')) s = s.slice(2, -2).trim()
  return s || 'True'
}
